### ISSUE TITLE
getFollowersFromDB & getQuestsFromDB returns undefined

### ISSUE THREAD

**Issue by JustinHorn** [Ey-Jay/rickysquest#24]
On completing a quiz, I get the following error:

![error](https://user-images.githubusercontent.com/49308113/90772457-ee87db80-e2f4-11ea-82ed-0a8e1c41e34b.PNG)

fixed this by

```
export const getFollowersFromDB = async (uid) => {
  const followers = await db
    .collection('users')
    .doc(uid)
    .get()
    .then((res) => {
      return res.data().followers;
    })
    .catch((err) => console.error(err));

  return followers || []; // previously just return quests
}
```

and

```
export const getQuestsFromDB = async (uid) => {
  const quests = await db
    .collection('users')
    .doc(uid)
    .get()
    .then((res) => {
      return res.data().quests;
    })
    .catch((err) => console.error(err));

  return quests || [];// previously just return quests
};
```

**Comment by jossdoe** [comment]
This is most likely due to you still being logged in after us having deleted the user documents manually in the Firestore. Technically, that fix isn't needed for the App to work, since the Firestore should return an empty Array if no quests are completed. The undefined value only occurs when there is no user document, which should never happen in production – because it's created on login. Logging out and back in should fix that for you. (However, the null check doesn't hurt either.)
